//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a T4 template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Windows;


namespace TerminalMACS.Home.I18nResources
{
	public static class Language
	{
		public static readonly ComponentResourceKey MainTabItem_Timeline = new ComponentResourceKey(typeof(UiResource), nameof(MainTabItem_Timeline));
		public static readonly ComponentResourceKey MainTabItm_Header = new ComponentResourceKey(typeof(UiResource), nameof(MainTabItm_Header));
		public static readonly ComponentResourceKey Timeline_AddAbpVNextSeverProject = new ComponentResourceKey(typeof(UiResource), nameof(Timeline_AddAbpVNextSeverProject));
		public static readonly ComponentResourceKey Timeline_AddEmptyClientApp = new ComponentResourceKey(typeof(UiResource), nameof(Timeline_AddEmptyClientApp));
		public static readonly ComponentResourceKey Timeline_AddNotifyIcon = new ComponentResourceKey(typeof(UiResource), nameof(Timeline_AddNotifyIcon));
		public static readonly ComponentResourceKey Timeline_AddWPFManagerProject = new ComponentResourceKey(typeof(UiResource), nameof(Timeline_AddWPFManagerProject));
		public static readonly ComponentResourceKey Timeline_ClientAppBaseInfo = new ComponentResourceKey(typeof(UiResource), nameof(Timeline_ClientAppBaseInfo));
		public static readonly ComponentResourceKey Timeline_ClientAppCompleteContactRead = new ComponentResourceKey(typeof(UiResource), nameof(Timeline_ClientAppCompleteContactRead));
		public static readonly ComponentResourceKey Timeline_ClientAppVersion1 = new ComponentResourceKey(typeof(UiResource), nameof(Timeline_ClientAppVersion1));
		public static readonly ComponentResourceKey Timeline_InitializeProject = new ComponentResourceKey(typeof(UiResource), nameof(Timeline_InitializeProject));
		public static readonly ComponentResourceKey Timeline_WPFManagerStructureOver = new ComponentResourceKey(typeof(UiResource), nameof(Timeline_WPFManagerStructureOver));
	}
}