//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TerminalMACS.Home.I18nResources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class UiResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UiResource() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TerminalMACS.Home.I18nResources.UiResource", typeof(UiResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Excellent interface display 的本地化字符串。
        /// </summary>
        internal static string MainTabItem_TestDemoDisplay {
            get {
                return ResourceManager.GetString("MainTabItem_TestDemoDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Timeline 的本地化字符串。
        /// </summary>
        internal static string MainTabItem_Timeline {
            get {
                return ResourceManager.GetString("MainTabItem_Timeline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Home 的本地化字符串。
        /// </summary>
        internal static string MainTabItm_Header {
            get {
                return ResourceManager.GetString("MainTabItm_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Pre knowledge preparation, add ABP vNext basic service project 的本地化字符串。
        /// </summary>
        internal static string Timeline_AddAbpVNextSeverProject {
            get {
                return ResourceManager.GetString("Timeline_AddAbpVNextSeverProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add empty client project 的本地化字符串。
        /// </summary>
        internal static string Timeline_AddEmptyClientApp {
            get {
                return ResourceManager.GetString("Timeline_AddEmptyClientApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add NotifyIcon 的本地化字符串。
        /// </summary>
        internal static string Timeline_AddNotifyIcon {
            get {
                return ResourceManager.GetString("Timeline_AddNotifyIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Confirm that the server adopts ABP vNext recommendation and adds WPF project 的本地化字符串。
        /// </summary>
        internal static string Timeline_AddWPFManagerProject {
            get {
                return ResourceManager.GetString("Timeline_AddWPFManagerProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Basic information acquisition of mobile client 的本地化字符串。
        /// </summary>
        internal static string Timeline_ClientAppBaseInfo {
            get {
                return ResourceManager.GetString("Timeline_ClientAppBaseInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Mobile client completes address book data reading 的本地化字符串。
        /// </summary>
        internal static string Timeline_ClientAppCompleteContactRead {
            get {
                return ResourceManager.GetString("Timeline_ClientAppCompleteContactRead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The first version of mobile client comes to an end, and other process modules are developed 的本地化字符串。
        /// </summary>
        internal static string Timeline_ClientAppVersion1 {
            get {
                return ResourceManager.GetString("Timeline_ClientAppVersion1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Initiallize project 的本地化字符串。
        /// </summary>
        internal static string Timeline_InitializeProject {
            get {
                return ResourceManager.GetString("Timeline_InitializeProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Build the first version of WPF management end, realize dynamic change of theme color, internationalization, localization and prism modularization 的本地化字符串。
        /// </summary>
        internal static string Timeline_WPFManagerStructureOver {
            get {
                return ResourceManager.GetString("Timeline_WPFManagerStructureOver", resourceCulture);
            }
        }
    }
}
