//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a T4 template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Windows;


namespace TerminalMACS.I18nResources
{
	public static class Language
	{
		public static readonly ComponentResourceKey About_AddAuthorWeChat = new ComponentResourceKey(typeof(UiResource), nameof(About_AddAuthorWeChat));
		public static readonly ComponentResourceKey About_AddUIDesignerWeChat = new ComponentResourceKey(typeof(UiResource), nameof(About_AddUIDesignerWeChat));
		public static readonly ComponentResourceKey About_AddWeChatOfficialAccount = new ComponentResourceKey(typeof(UiResource), nameof(About_AddWeChatOfficialAccount));
		public static readonly ComponentResourceKey About_BrowseOpenSourceFramework = new ComponentResourceKey(typeof(UiResource), nameof(About_BrowseOpenSourceFramework));
		public static readonly ComponentResourceKey About_ContactAuthor = new ComponentResourceKey(typeof(UiResource), nameof(About_ContactAuthor));
		public static readonly ComponentResourceKey About_JonQQGroup = new ComponentResourceKey(typeof(UiResource), nameof(About_JonQQGroup));
		public static readonly ComponentResourceKey About_TechExchange = new ComponentResourceKey(typeof(UiResource), nameof(About_TechExchange));
		public static readonly ComponentResourceKey About_Thanks = new ComponentResourceKey(typeof(UiResource), nameof(About_Thanks));
		public static readonly ComponentResourceKey AppTitle = new ComponentResourceKey(typeof(UiResource), nameof(AppTitle));
		public static readonly ComponentResourceKey Exit = new ComponentResourceKey(typeof(UiResource), nameof(Exit));
		public static readonly ComponentResourceKey MainMenu_About = new ComponentResourceKey(typeof(UiResource), nameof(MainMenu_About));
		public static readonly ComponentResourceKey MainMenu_CNBlogs = new ComponentResourceKey(typeof(UiResource), nameof(MainMenu_CNBlogs));
		public static readonly ComponentResourceKey MainMenu_Contact = new ComponentResourceKey(typeof(UiResource), nameof(MainMenu_Contact));
		public static readonly ComponentResourceKey MainMenu_Email = new ComponentResourceKey(typeof(UiResource), nameof(MainMenu_Email));
		public static readonly ComponentResourceKey MainMenu_Language = new ComponentResourceKey(typeof(UiResource), nameof(MainMenu_Language));
		public static readonly ComponentResourceKey MainMenu_QQGroup = new ComponentResourceKey(typeof(UiResource), nameof(MainMenu_QQGroup));
		public static readonly ComponentResourceKey MainMenu_Setting = new ComponentResourceKey(typeof(UiResource), nameof(MainMenu_Setting));
		public static readonly ComponentResourceKey MainMenu_SourceCode = new ComponentResourceKey(typeof(UiResource), nameof(MainMenu_SourceCode));
		public static readonly ComponentResourceKey MainMenu_SponsorshipAndSupport = new ComponentResourceKey(typeof(UiResource), nameof(MainMenu_SponsorshipAndSupport));
		public static readonly ComponentResourceKey MainMenu_TechSupport = new ComponentResourceKey(typeof(UiResource), nameof(MainMenu_TechSupport));
		public static readonly ComponentResourceKey MainMenu_ThemeColor = new ComponentResourceKey(typeof(UiResource), nameof(MainMenu_ThemeColor));
		public static readonly ComponentResourceKey MainMenu_TouTiao = new ComponentResourceKey(typeof(UiResource), nameof(MainMenu_TouTiao));
		public static readonly ComponentResourceKey PushMainWindow2Top = new ComponentResourceKey(typeof(UiResource), nameof(PushMainWindow2Top));
	}
}