//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TerminalMACS.I18nResources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class UiResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UiResource() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TerminalMACS.I18nResources.UiResource", typeof(UiResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Scan code to add author&apos;s wechat and wechat group 的本地化字符串。
        /// </summary>
        public static string About_AddAuthorWeChat {
            get {
                return ResourceManager.GetString("About_AddAuthorWeChat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Scan code concerns WeChat official account: Dotnet9 的本地化字符串。
        /// </summary>
        public static string About_AddWeChatOfficialAccount {
            get {
                return ResourceManager.GetString("About_AddWeChatOfficialAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Browse open source framework 的本地化字符串。
        /// </summary>
        public static string About_BrowseOpenSourceFramework {
            get {
                return ResourceManager.GetString("About_BrowseOpenSourceFramework", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Contact author 的本地化字符串。
        /// </summary>
        public static string About_ContactAuthor {
            get {
                return ResourceManager.GetString("About_ContactAuthor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Click to join the group chat 的本地化字符串。
        /// </summary>
        public static string About_JonQQGroup {
            get {
                return ResourceManager.GetString("About_JonQQGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Technical exchange 的本地化字符串。
        /// </summary>
        public static string About_TechExchange {
            get {
                return ResourceManager.GetString("About_TechExchange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Thanks for the open source framework 的本地化字符串。
        /// </summary>
        public static string About_Thanks {
            get {
                return ResourceManager.GetString("About_Thanks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Terminal management and check system 的本地化字符串。
        /// </summary>
        public static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Exit application 的本地化字符串。
        /// </summary>
        public static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 About 的本地化字符串。
        /// </summary>
        public static string MainMenu_About {
            get {
                return ResourceManager.GetString("MainMenu_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 cnblogs 的本地化字符串。
        /// </summary>
        public static string MainMenu_CNBlogs {
            get {
                return ResourceManager.GetString("MainMenu_CNBlogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Contact 的本地化字符串。
        /// </summary>
        public static string MainMenu_Contact {
            get {
                return ResourceManager.GetString("MainMenu_Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 E-mail 的本地化字符串。
        /// </summary>
        public static string MainMenu_Email {
            get {
                return ResourceManager.GetString("MainMenu_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Language 的本地化字符串。
        /// </summary>
        public static string MainMenu_Language {
            get {
                return ResourceManager.GetString("MainMenu_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 QQ group 的本地化字符串。
        /// </summary>
        public static string MainMenu_QQGroup {
            get {
                return ResourceManager.GetString("MainMenu_QQGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Setting 的本地化字符串。
        /// </summary>
        public static string MainMenu_Setting {
            get {
                return ResourceManager.GetString("MainMenu_Setting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Source code 的本地化字符串。
        /// </summary>
        public static string MainMenu_SourceCode {
            get {
                return ResourceManager.GetString("MainMenu_SourceCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sponsorship support 的本地化字符串。
        /// </summary>
        public static string MainMenu_SponsorshipAndSupport {
            get {
                return ResourceManager.GetString("MainMenu_SponsorshipAndSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Technical support 的本地化字符串。
        /// </summary>
        public static string MainMenu_TechSupport {
            get {
                return ResourceManager.GetString("MainMenu_TechSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Theme color 的本地化字符串。
        /// </summary>
        public static string MainMenu_ThemeColor {
            get {
                return ResourceManager.GetString("MainMenu_ThemeColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Tou Tiao 的本地化字符串。
        /// </summary>
        public static string MainMenu_TouTiao {
            get {
                return ResourceManager.GetString("MainMenu_TouTiao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open main window 的本地化字符串。
        /// </summary>
        public static string PushMainWindow2Top {
            get {
                return ResourceManager.GetString("PushMainWindow2Top", resourceCulture);
            }
        }
    }
}
