//------------------------------------------------------------------------------  
// <auto-generated>  
//     This code was generated by a tool.  
//     Changes to this file may cause incorrect behavior and will be lost if  
//     the code is regenerated.  
// </auto-generated>  
//------------------------------------------------------------------------------
namespace Localization
{
    public static class Test
    {
        public static readonly string Title = "Localization.Test.Title";
        public static readonly string AnimatedMenuBtnContent = "Localization.Test.AnimatedMenuBtnContent";
        public static readonly string AppUsageDashboardBtnContent = "Localization.Test.AppUsageDashboardBtnContent";
        public static readonly string Dashboard2BtnContent = "Localization.Test.Dashboard2BtnContent";
        public static readonly string DrawerMenuBtnContent = "Localization.Test.DrawerMenuBtnContent";
        public static readonly string FoodBtnContent = "Localization.Test.FoodBtnContent";
        public static readonly string InstagramRedesignBtnContent = "Localization.Test.InstagramRedesignBtnContent";
        public static readonly string LoginView1BtnContent = "Localization.Test.LoginView1BtnContent";
        public static readonly string LoginView2BtnContent = "Localization.Test.LoginView2BtnContent";
        public static readonly string LoLGoalBtnContent = "Localization.Test.LoLGoalBtnContent";
        public static readonly string MenuChangeBtnContent = "Localization.Test.MenuChangeBtnContent";
        public static readonly string MusicPlayer1BtnContent = "Localization.Test.MusicPlayer1BtnContent";
    }
}
namespace Localization
{
    public static class FoodAppLoginView
    {
        public static readonly string Cancel = "Localization.FoodAppLoginView.Cancel";
        public static readonly string Fail = "Localization.FoodAppLoginView.Fail";
        public static readonly string IsLogining = "Localization.FoodAppLoginView.IsLogining";
        public static readonly string Login = "Localization.FoodAppLoginView.Login";
        public static readonly string MyFoodApp = "Localization.FoodAppLoginView.MyFoodApp";
        public static readonly string UserName = "Localization.FoodAppLoginView.UserName";
        public static readonly string Password = "Localization.FoodAppLoginView.Password";
        public static readonly string RememberMe = "Localization.FoodAppLoginView.RememberMe";
        public static readonly string Success = "Localization.FoodAppLoginView.Success";
    }
}
