//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a T4 template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Windows;


namespace TerminalMACS.TestDemo.I18nResources
{
	public static class Language
	{
		public static readonly ComponentResourceKey FoodAppLoginView_Cancel = new ComponentResourceKey(typeof(UiResource), nameof(FoodAppLoginView_Cancel));
		public static readonly ComponentResourceKey FoodAppLoginView_Fail = new ComponentResourceKey(typeof(UiResource), nameof(FoodAppLoginView_Fail));
		public static readonly ComponentResourceKey FoodAppLoginView_IsLogining = new ComponentResourceKey(typeof(UiResource), nameof(FoodAppLoginView_IsLogining));
		public static readonly ComponentResourceKey FoodAppLoginView_Login = new ComponentResourceKey(typeof(UiResource), nameof(FoodAppLoginView_Login));
		public static readonly ComponentResourceKey FoodAppLoginView_MyFoodApp = new ComponentResourceKey(typeof(UiResource), nameof(FoodAppLoginView_MyFoodApp));
		public static readonly ComponentResourceKey FoodAppLoginView_Password = new ComponentResourceKey(typeof(UiResource), nameof(FoodAppLoginView_Password));
		public static readonly ComponentResourceKey FoodAppLoginView_RememberMe = new ComponentResourceKey(typeof(UiResource), nameof(FoodAppLoginView_RememberMe));
		public static readonly ComponentResourceKey FoodAppLoginView_Success = new ComponentResourceKey(typeof(UiResource), nameof(FoodAppLoginView_Success));
		public static readonly ComponentResourceKey FoodAppLoginView_UserName = new ComponentResourceKey(typeof(UiResource), nameof(FoodAppLoginView_UserName));
		public static readonly ComponentResourceKey MainTabItem_AppUsageDashboardBtnContent = new ComponentResourceKey(typeof(UiResource), nameof(MainTabItem_AppUsageDashboardBtnContent));
		public static readonly ComponentResourceKey MainTabItem_FoodBtnContent = new ComponentResourceKey(typeof(UiResource), nameof(MainTabItem_FoodBtnContent));
		public static readonly ComponentResourceKey MainTabItem_Header = new ComponentResourceKey(typeof(UiResource), nameof(MainTabItem_Header));
		public static readonly ComponentResourceKey MainTabItem_LoginView1BtnContent = new ComponentResourceKey(typeof(UiResource), nameof(MainTabItem_LoginView1BtnContent));
		public static readonly ComponentResourceKey MainTabItem_LoginView2BtnContent = new ComponentResourceKey(typeof(UiResource), nameof(MainTabItem_LoginView2BtnContent));
	}
}