//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TerminalMACS.TestDemo.I18nResources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class UiResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UiResource() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TerminalMACS.TestDemo.I18nResources.UiResource", typeof(UiResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Cancel 的本地化字符串。
        /// </summary>
        internal static string FoodAppLoginView_Cancel {
            get {
                return ResourceManager.GetString("FoodAppLoginView_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Login failed, please login again! 的本地化字符串。
        /// </summary>
        internal static string FoodAppLoginView_Fail {
            get {
                return ResourceManager.GetString("FoodAppLoginView_Fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Logging in... 的本地化字符串。
        /// </summary>
        internal static string FoodAppLoginView_IsLogining {
            get {
                return ResourceManager.GetString("FoodAppLoginView_IsLogining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sign in 的本地化字符串。
        /// </summary>
        internal static string FoodAppLoginView_Login {
            get {
                return ResourceManager.GetString("FoodAppLoginView_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 My food app 的本地化字符串。
        /// </summary>
        internal static string FoodAppLoginView_MyFoodApp {
            get {
                return ResourceManager.GetString("FoodAppLoginView_MyFoodApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Password 的本地化字符串。
        /// </summary>
        internal static string FoodAppLoginView_Password {
            get {
                return ResourceManager.GetString("FoodAppLoginView_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Remember me 的本地化字符串。
        /// </summary>
        internal static string FoodAppLoginView_RememberMe {
            get {
                return ResourceManager.GetString("FoodAppLoginView_RememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Login successful 的本地化字符串。
        /// </summary>
        internal static string FoodAppLoginView_Success {
            get {
                return ResourceManager.GetString("FoodAppLoginView_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 User Name 的本地化字符串。
        /// </summary>
        internal static string FoodAppLoginView_UserName {
            get {
                return ResourceManager.GetString("FoodAppLoginView_UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Modile useage dashboard 的本地化字符串。
        /// </summary>
        internal static string MainTabItem_AppUsageDashboardBtnContent {
            get {
                return ResourceManager.GetString("MainTabItem_AppUsageDashboardBtnContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Dashboard 2 的本地化字符串。
        /// </summary>
        internal static string MainTabItem_Dashboard2BtnContent {
            get {
                return ResourceManager.GetString("MainTabItem_Dashboard2BtnContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Food app login 的本地化字符串。
        /// </summary>
        internal static string MainTabItem_FoodBtnContent {
            get {
                return ResourceManager.GetString("MainTabItem_FoodBtnContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Test demos 的本地化字符串。
        /// </summary>
        internal static string MainTabItem_Header {
            get {
                return ResourceManager.GetString("MainTabItem_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Simple login form 1 的本地化字符串。
        /// </summary>
        internal static string MainTabItem_LoginView1BtnContent {
            get {
                return ResourceManager.GetString("MainTabItem_LoginView1BtnContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Simple login form 2 的本地化字符串。
        /// </summary>
        internal static string MainTabItem_LoginView2BtnContent {
            get {
                return ResourceManager.GetString("MainTabItem_LoginView2BtnContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Simple music player 1 的本地化字符串。
        /// </summary>
        internal static string MainTabItem_MusicPlayer1BtnContent {
            get {
                return ResourceManager.GetString("MainTabItem_MusicPlayer1BtnContent", resourceCulture);
            }
        }
    }
}
