//------------------------------------------------------------------------------  
// <auto-generated>  
//     This code was generated by a tool.  
//     Changes to this file may cause incorrect behavior and will be lost if  
//     the code is regenerated.  
// </auto-generated>  
//------------------------------------------------------------------------------
namespace Localization
{
    public static class CusSplashScreen
    {
        public static readonly string Title = "Localization.CusSplashScreen.Title";
    }
}
namespace Localization
{
    public static class Login
    {
        public static readonly string Title = "Localization.Login.Title";
        public static readonly string DoYouHaveAccount = "Localization.Login.DoYouHaveAccount";
        public static readonly string CreateAccount = "Localization.Login.CreateAccount";
        public static readonly string Account = "Localization.Login.Account";
        public static readonly string Password = "Localization.Login.Password";
        public static readonly string NotLie = "Localization.Login.NotLie";
        public static readonly string RememberMe = "Localization.Login.RememberMe";
        public static readonly string ForgotPassword = "Localization.Login.ForgotPassword";
        public static readonly string ThirdLogin = "Localization.Login.ThirdLogin";
        public static readonly string Welcome = "Localization.Login.Welcome";
        public static readonly string Slogon = "Localization.Login.Slogon";
    }
}
namespace Localization
{
    public static class MainWindow
    {
        public static readonly string Title = "Localization.MainWindow.Title";
        public static readonly string Exit = "Localization.MainWindow.Exit";
        public static readonly string About = "Localization.MainWindow.About";
        public static readonly string CNBlogs = "Localization.MainWindow.CNBlogs";
        public static readonly string Contact = "Localization.MainWindow.Contact";
        public static readonly string Email = "Localization.MainWindow.Email";
        public static readonly string Language = "Localization.MainWindow.Language";
        public static readonly string QQGroup = "Localization.MainWindow.QQGroup";
        public static readonly string Setting = "Localization.MainWindow.Setting";
        public static readonly string SourceCode = "Localization.MainWindow.SourceCode";
        public static readonly string SponsorshipAndSupport = "Localization.MainWindow.SponsorshipAndSupport";
        public static readonly string TechSupport = "Localization.MainWindow.TechSupport";
        public static readonly string ThemeColor = "Localization.MainWindow.ThemeColor";
        public static readonly string TouTiao = "Localization.MainWindow.TouTiao";
        public static readonly string PushMainWindow2Top = "Localization.MainWindow.PushMainWindow2Top";
    }
}
namespace Localization
{
    public static class About
    {
        public static readonly string Title = "Localization.About.Title";
        public static readonly string AddAuthorWeChat = "Localization.About.AddAuthorWeChat";
        public static readonly string AddWeChatOfficialAccount = "Localization.About.AddWeChatOfficialAccount";
        public static readonly string BrowseOpenSourceFramework = "Localization.About.BrowseOpenSourceFramework";
        public static readonly string ContactAuthor = "Localization.About.ContactAuthor";
        public static readonly string JoinQQGroup = "Localization.About.JoinQQGroup";
        public static readonly string TechExchange = "Localization.About.TechExchange";
        public static readonly string Thanks = "Localization.About.Thanks";
    }
}
