//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a T4 template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


using System.Windows.Data;

namespace WpfExtensions.Xaml.Markup
{
    public partial class ComposeExtension
    {
		/*
		 * Have to list these constructor overloads here,
		 * because the stupid xaml does not support the "params" keyword.
		 * e.g.: ctor(params object[] converters) cannot be used.
		 */

		public ComposeExtension() { }

		public ComposeExtension(object item0, object item1)
		{
			Converters.Add(item0);
			Converters.Add(item1);
		}

		public ComposeExtension(object item0, object item1, object item2)
		{
			Converters.Add(item0);
			Converters.Add(item1);
			Converters.Add(item2);
		}

		public ComposeExtension(object item0, object item1, object item2, object item3)
		{
			Converters.Add(item0);
			Converters.Add(item1);
			Converters.Add(item2);
			Converters.Add(item3);
		}

		public ComposeExtension(object item0, object item1, object item2, object item3, object item4)
		{
			Converters.Add(item0);
			Converters.Add(item1);
			Converters.Add(item2);
			Converters.Add(item3);
			Converters.Add(item4);
		}

		public ComposeExtension(object item0, object item1, object item2, object item3, object item4, object item5)
		{
			Converters.Add(item0);
			Converters.Add(item1);
			Converters.Add(item2);
			Converters.Add(item3);
			Converters.Add(item4);
			Converters.Add(item5);
		}

		public ComposeExtension(object item0, object item1, object item2, object item3, object item4, object item5, object item6)
		{
			Converters.Add(item0);
			Converters.Add(item1);
			Converters.Add(item2);
			Converters.Add(item3);
			Converters.Add(item4);
			Converters.Add(item5);
			Converters.Add(item6);
		}

		public ComposeExtension(object item0, object item1, object item2, object item3, object item4, object item5, object item6, object item7)
		{
			Converters.Add(item0);
			Converters.Add(item1);
			Converters.Add(item2);
			Converters.Add(item3);
			Converters.Add(item4);
			Converters.Add(item5);
			Converters.Add(item6);
			Converters.Add(item7);
		}

		public ComposeExtension(object item0, object item1, object item2, object item3, object item4, object item5, object item6, object item7, object item8)
		{
			Converters.Add(item0);
			Converters.Add(item1);
			Converters.Add(item2);
			Converters.Add(item3);
			Converters.Add(item4);
			Converters.Add(item5);
			Converters.Add(item6);
			Converters.Add(item7);
			Converters.Add(item8);
		}

		public ComposeExtension(object item0, object item1, object item2, object item3, object item4, object item5, object item6, object item7, object item8, object item9)
		{
			Converters.Add(item0);
			Converters.Add(item1);
			Converters.Add(item2);
			Converters.Add(item3);
			Converters.Add(item4);
			Converters.Add(item5);
			Converters.Add(item6);
			Converters.Add(item7);
			Converters.Add(item8);
			Converters.Add(item9);
		}

		public ComposeExtension(object item0, object item1, object item2, object item3, object item4, object item5, object item6, object item7, object item8, object item9, object item10)
		{
			Converters.Add(item0);
			Converters.Add(item1);
			Converters.Add(item2);
			Converters.Add(item3);
			Converters.Add(item4);
			Converters.Add(item5);
			Converters.Add(item6);
			Converters.Add(item7);
			Converters.Add(item8);
			Converters.Add(item9);
			Converters.Add(item10);
		}

		public ComposeExtension(object item0, object item1, object item2, object item3, object item4, object item5, object item6, object item7, object item8, object item9, object item10, object item11)
		{
			Converters.Add(item0);
			Converters.Add(item1);
			Converters.Add(item2);
			Converters.Add(item3);
			Converters.Add(item4);
			Converters.Add(item5);
			Converters.Add(item6);
			Converters.Add(item7);
			Converters.Add(item8);
			Converters.Add(item9);
			Converters.Add(item10);
			Converters.Add(item11);
		}

		public ComposeExtension(object item0, object item1, object item2, object item3, object item4, object item5, object item6, object item7, object item8, object item9, object item10, object item11, object item12)
		{
			Converters.Add(item0);
			Converters.Add(item1);
			Converters.Add(item2);
			Converters.Add(item3);
			Converters.Add(item4);
			Converters.Add(item5);
			Converters.Add(item6);
			Converters.Add(item7);
			Converters.Add(item8);
			Converters.Add(item9);
			Converters.Add(item10);
			Converters.Add(item11);
			Converters.Add(item12);
		}

		public ComposeExtension(object item0, object item1, object item2, object item3, object item4, object item5, object item6, object item7, object item8, object item9, object item10, object item11, object item12, object item13)
		{
			Converters.Add(item0);
			Converters.Add(item1);
			Converters.Add(item2);
			Converters.Add(item3);
			Converters.Add(item4);
			Converters.Add(item5);
			Converters.Add(item6);
			Converters.Add(item7);
			Converters.Add(item8);
			Converters.Add(item9);
			Converters.Add(item10);
			Converters.Add(item11);
			Converters.Add(item12);
			Converters.Add(item13);
		}

		public ComposeExtension(object item0, object item1, object item2, object item3, object item4, object item5, object item6, object item7, object item8, object item9, object item10, object item11, object item12, object item13, object item14)
		{
			Converters.Add(item0);
			Converters.Add(item1);
			Converters.Add(item2);
			Converters.Add(item3);
			Converters.Add(item4);
			Converters.Add(item5);
			Converters.Add(item6);
			Converters.Add(item7);
			Converters.Add(item8);
			Converters.Add(item9);
			Converters.Add(item10);
			Converters.Add(item11);
			Converters.Add(item12);
			Converters.Add(item13);
			Converters.Add(item14);
		}

		public ComposeExtension(object item0, object item1, object item2, object item3, object item4, object item5, object item6, object item7, object item8, object item9, object item10, object item11, object item12, object item13, object item14, object item15)
		{
			Converters.Add(item0);
			Converters.Add(item1);
			Converters.Add(item2);
			Converters.Add(item3);
			Converters.Add(item4);
			Converters.Add(item5);
			Converters.Add(item6);
			Converters.Add(item7);
			Converters.Add(item8);
			Converters.Add(item9);
			Converters.Add(item10);
			Converters.Add(item11);
			Converters.Add(item12);
			Converters.Add(item13);
			Converters.Add(item14);
			Converters.Add(item15);
		}

    }
}
