//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a T4 template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


using System.Windows.Data;
using System.Windows;

namespace WpfExtensions.Xaml.Markup
{
    public partial class I18nStringExtension
    {
		/*
		 * Have to list these constructor overloads here,
		 * because the stupid xaml does not support the "params" keyword.
		 * e.g.: ctor(params object[] converters) cannot be used.
		 */

		public I18nStringExtension() 
		{
			Converter = new MultiValueConverter(this);
			Args = new ArgCollection(this);
		}

		private I18nStringExtension(ComponentResourceKey key)
			: this()
		{
			Key = key;
			Bindings.Add(new Binding(nameof(I18nSource.Value))
			{
				Source = new I18nSource(key),
				Mode = BindingMode.OneWay,
				Converter = ResourceConverter
			});
		}

		public I18nStringExtension(ComponentResourceKey key, object item0)
			: this(key)
		{
			Args.Add(item0);
		}

		public I18nStringExtension(ComponentResourceKey key, object item0, object item1)
			: this(key)
		{
			Args.Add(item0);
			Args.Add(item1);
		}

		public I18nStringExtension(ComponentResourceKey key, object item0, object item1, object item2)
			: this(key)
		{
			Args.Add(item0);
			Args.Add(item1);
			Args.Add(item2);
		}

		public I18nStringExtension(ComponentResourceKey key, object item0, object item1, object item2, object item3)
			: this(key)
		{
			Args.Add(item0);
			Args.Add(item1);
			Args.Add(item2);
			Args.Add(item3);
		}

		public I18nStringExtension(ComponentResourceKey key, object item0, object item1, object item2, object item3, object item4)
			: this(key)
		{
			Args.Add(item0);
			Args.Add(item1);
			Args.Add(item2);
			Args.Add(item3);
			Args.Add(item4);
		}

		public I18nStringExtension(ComponentResourceKey key, object item0, object item1, object item2, object item3, object item4, object item5)
			: this(key)
		{
			Args.Add(item0);
			Args.Add(item1);
			Args.Add(item2);
			Args.Add(item3);
			Args.Add(item4);
			Args.Add(item5);
		}

		public I18nStringExtension(ComponentResourceKey key, object item0, object item1, object item2, object item3, object item4, object item5, object item6)
			: this(key)
		{
			Args.Add(item0);
			Args.Add(item1);
			Args.Add(item2);
			Args.Add(item3);
			Args.Add(item4);
			Args.Add(item5);
			Args.Add(item6);
		}

		public I18nStringExtension(ComponentResourceKey key, object item0, object item1, object item2, object item3, object item4, object item5, object item6, object item7)
			: this(key)
		{
			Args.Add(item0);
			Args.Add(item1);
			Args.Add(item2);
			Args.Add(item3);
			Args.Add(item4);
			Args.Add(item5);
			Args.Add(item6);
			Args.Add(item7);
		}

		public I18nStringExtension(ComponentResourceKey key, object item0, object item1, object item2, object item3, object item4, object item5, object item6, object item7, object item8)
			: this(key)
		{
			Args.Add(item0);
			Args.Add(item1);
			Args.Add(item2);
			Args.Add(item3);
			Args.Add(item4);
			Args.Add(item5);
			Args.Add(item6);
			Args.Add(item7);
			Args.Add(item8);
		}

		public I18nStringExtension(ComponentResourceKey key, object item0, object item1, object item2, object item3, object item4, object item5, object item6, object item7, object item8, object item9)
			: this(key)
		{
			Args.Add(item0);
			Args.Add(item1);
			Args.Add(item2);
			Args.Add(item3);
			Args.Add(item4);
			Args.Add(item5);
			Args.Add(item6);
			Args.Add(item7);
			Args.Add(item8);
			Args.Add(item9);
		}

		public I18nStringExtension(ComponentResourceKey key, object item0, object item1, object item2, object item3, object item4, object item5, object item6, object item7, object item8, object item9, object item10)
			: this(key)
		{
			Args.Add(item0);
			Args.Add(item1);
			Args.Add(item2);
			Args.Add(item3);
			Args.Add(item4);
			Args.Add(item5);
			Args.Add(item6);
			Args.Add(item7);
			Args.Add(item8);
			Args.Add(item9);
			Args.Add(item10);
		}

		public I18nStringExtension(ComponentResourceKey key, object item0, object item1, object item2, object item3, object item4, object item5, object item6, object item7, object item8, object item9, object item10, object item11)
			: this(key)
		{
			Args.Add(item0);
			Args.Add(item1);
			Args.Add(item2);
			Args.Add(item3);
			Args.Add(item4);
			Args.Add(item5);
			Args.Add(item6);
			Args.Add(item7);
			Args.Add(item8);
			Args.Add(item9);
			Args.Add(item10);
			Args.Add(item11);
		}

		public I18nStringExtension(ComponentResourceKey key, object item0, object item1, object item2, object item3, object item4, object item5, object item6, object item7, object item8, object item9, object item10, object item11, object item12)
			: this(key)
		{
			Args.Add(item0);
			Args.Add(item1);
			Args.Add(item2);
			Args.Add(item3);
			Args.Add(item4);
			Args.Add(item5);
			Args.Add(item6);
			Args.Add(item7);
			Args.Add(item8);
			Args.Add(item9);
			Args.Add(item10);
			Args.Add(item11);
			Args.Add(item12);
		}

		public I18nStringExtension(ComponentResourceKey key, object item0, object item1, object item2, object item3, object item4, object item5, object item6, object item7, object item8, object item9, object item10, object item11, object item12, object item13)
			: this(key)
		{
			Args.Add(item0);
			Args.Add(item1);
			Args.Add(item2);
			Args.Add(item3);
			Args.Add(item4);
			Args.Add(item5);
			Args.Add(item6);
			Args.Add(item7);
			Args.Add(item8);
			Args.Add(item9);
			Args.Add(item10);
			Args.Add(item11);
			Args.Add(item12);
			Args.Add(item13);
		}

		public I18nStringExtension(ComponentResourceKey key, object item0, object item1, object item2, object item3, object item4, object item5, object item6, object item7, object item8, object item9, object item10, object item11, object item12, object item13, object item14)
			: this(key)
		{
			Args.Add(item0);
			Args.Add(item1);
			Args.Add(item2);
			Args.Add(item3);
			Args.Add(item4);
			Args.Add(item5);
			Args.Add(item6);
			Args.Add(item7);
			Args.Add(item8);
			Args.Add(item9);
			Args.Add(item10);
			Args.Add(item11);
			Args.Add(item12);
			Args.Add(item13);
			Args.Add(item14);
		}

		public I18nStringExtension(ComponentResourceKey key, object item0, object item1, object item2, object item3, object item4, object item5, object item6, object item7, object item8, object item9, object item10, object item11, object item12, object item13, object item14, object item15)
			: this(key)
		{
			Args.Add(item0);
			Args.Add(item1);
			Args.Add(item2);
			Args.Add(item3);
			Args.Add(item4);
			Args.Add(item5);
			Args.Add(item6);
			Args.Add(item7);
			Args.Add(item8);
			Args.Add(item9);
			Args.Add(item10);
			Args.Add(item11);
			Args.Add(item12);
			Args.Add(item13);
			Args.Add(item14);
			Args.Add(item15);
		}

    }
}
