//------------------------------------------------------------------------------  
// <auto-generated>  
//     This code was generated by a tool.  
//     Changes to this file may cause incorrect behavior and will be lost if  
//     the code is regenerated.  
// </auto-generated>  
//------------------------------------------------------------------------------
namespace Localization
{
    public static class Home
    {
        public static readonly string Title = "Localization.Home.Title";
        public static readonly string TimeLine = "Localization.Home.TimeLine";
        public static readonly string TestDemoDisplay = "Localization.Home.TestDemoDisplay";
    }
}
namespace Localization
{
    public static class TimeLine
    {
        public static readonly string AddAbpVNextSeverProject = "Localization.TimeLine.AddAbpVNextSeverProject";
        public static readonly string AddEmptyClientApp = "Localization.TimeLine.AddEmptyClientApp";
        public static readonly string AddNotifyIcon = "Localization.TimeLine.AddNotifyIcon";
        public static readonly string AddWPFManagerProject = "Localization.TimeLine.AddWPFManagerProject";
        public static readonly string ClientAppBaseInfo = "Localization.TimeLine.ClientAppBaseInfo";
        public static readonly string ClientAppCompleteContactRead = "Localization.TimeLine.ClientAppCompleteContactRead";
        public static readonly string ClientAppVersion1 = "Localization.TimeLine.ClientAppVersion1";
        public static readonly string InitializeProject = "Localization.TimeLine.InitializeProject";
        public static readonly string WPFManagerStructureOver = "Localization.TimeLine.WPFManagerStructureOver";
    }
}
