//------------------------------------------------------------------------------  
// <auto-generated>  
//     This code was generated by a tool.  
//     Changes to this file may cause incorrect behavior and will be lost if  
//     the code is regenerated.  
// </auto-generated>  
//------------------------------------------------------------------------------
namespace Localization
{
    public static class Server
    {
        public static readonly string Title = "Localization.Server.Title";
    }
}
namespace Localization
{
    public static class ChatTest
    {
        public static readonly string MockSortCount = "Localization.ChatTest.MockSortCount";
        public static readonly string ExchangeSleepTime = "Localization.ChatTest.ExchangeSleepTime";
        public static readonly string Init = "Localization.ChatTest.Init";
        public static readonly string Start = "Localization.ChatTest.Start";
    }
}
